apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyuirseraw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyuirseraw
  template:
    metadata:
      labels:
        app: gyuirseraw
    spec:
      containers:
      - image: okteto.dev/gyuirseraw:latest
        name: gyuirseraw
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: ""
        - name: Vless_UUID
          value: "54abbea6-2ad6-4854-8679-a83d61bc1b3e"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "54abbea6-2ad6-4854-8679-a83d61bc1b3e"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
